name: AutoViP
main: org.mcforge.vhpontes.AutoViP
version: 0.25-dev
load: POSTWORLD
author: [vhpontes]
website: http://mcforge.org

commands:
   av:
      description: AutoViP Plugin Commands
      permission: autovip.av
      permission-message: You don't have permission to use this command.
      
permissions:
    autovip.av.*:
        description: Gives access to all AutoViP commands
        children:
            autovip.av.reload: true
            autovip.av.list: true
            autovip.av.endvip: true
            autovip.av.use: true
            autovip.av.check: true
            autovip.av.info: true
    autovip.av.admin.*:
        description: Gives access to admin AutoViP commands
        children:
            autovip.av.list: true
            autovip.av.endvip: true
            autovip.av.use: true
            autovip.av.check: true
            autovip.av.info: true
    autovip.av.user.*:
        description: Gives access to user AutoViP commands
        children:
            autovip.av.use: true
            autovip.av.check: true
            autovip.av.info: true
    autovip.av.reload:
        description: Reload plugin config file
        default: op
    autovip.av.list:
        description: List all avaliable codes
        default: op
    autovip.av.endvip:
        description: End ViP of a player
        default: op
    autovip.av.use:
        description: Use ViP code to promote
        default: false
    autovip.av.check:
        description: Validate ViP code
        default: false
    autovip.av.info:
        description: Informations of ViP player
        default: true
